---
# defaults file for wordpress
mysql_root_password: 12345678
wordpress_user_password: 12345678
dbhost: '%' #database-user-host, values: localhost, %
dbuser: wp-user
wpdb: wordpress
install_type: server
rdshost: localhost