---
- name: Install mitogen
  hosts: localhost
  connection: local
  become: true
  become_method: sudo
  roles:
    - robertdebock.bootstrap
    - robertdebock.core_dependencies
    - robertdebock.epel
    - robertdebock.python_pip
    - robertdebock.mitogen