- name: Install epel release repo for php
  yum:
    name: https://repo.mysql.com/mysql80-community-release-el7-3.noarch.rpm
    state: present
- name: Disable other mysql repo entries
  shell: sed -i 's/enabled=1/enabled=0/' /etc/yum.repos.d/mysql-community.repo
- name: Install MYSQL 8 community client and server
  yum:
    name: "{{ item }}"
    enablerepo: mysql80-community
    state: present
  loop:
     - mysql-community-server
     - mysql-community-client
- name: Start and enable mysql
  service:
   name: mysqld
   state: restarted
   enabled: yes
- name: Install mysqld python libary for Ansible
  package:
    name: MySQL-python
    state: present
- name: Set mysql root password
  mysql_user:
    name: 'root'
    host_all: true
    password: "{{ mysql_root_password }}"
    state: present
- name: Create wordpress database
  mysql_db:
    name: "{{ wpdb }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
- name: Create wordpress user
  mysql_user:
    name: "{{ dbuser }}"
    host: "{{ dbhost }}"
    priv: 'wordpress.*:ALL'
    password: "{{ wordpress_user_password }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"


