---
- name: Install mysqld python libary for Ansible
  package:
    name: MySQL-python
    state: present
- name: Create wordpress database
  mysql_db:
    name: "{{ wpdb }}"
    login_host: "{{ rdshost }}"
    state: present
    login_user: root
    login_password: "N$=]:%9;F7z%DX!X"
- name: Create wordpress user
  mysql_user:
    name: "{{ dbuser }}"
    host: "{{ dbhost }}"
    priv: '{{ wpdb }}.*:ALL'
    password: "{{ wordpress_user_password }}"
    state: present
    login_host: "{{ rdshost }}"
    login_user: root
    login_password: "N$=]:%9;F7z%DX!X"
#- name: Change wordpress user host
#  mysql_user:
#    name: "{{ dbuser }}"
#    host_all: yes
#    login_host: "{{ rdshost }}"
#    login_user: root
#    login_password: "N$=]:%9;F7z%DX!X"