- name: Install epel release
  yum:
    name: https://repo.mysql.com/mysql80-community-release-el7-3.noarch.rpm
    state: present
- name: Disable other mysql repo entries
  shell: sed -i 's/enabled=1/enabled=0/' /etc/yum.repos.d/mysql-community.repo
- name: Install MYSQL 8 community client and server
  yum:
    name: "{{ item }}"
    enablerepo: mysql80-community
    state: present
  loop:
     - mysql-community-server
     - mysql-community-client
- name: Change database username in wp-config
  shell: sed -i 's/# default-authentication-plugin=mysql_native_password/default-authentication-plugin=mysql_native_password/g' my.cnf
  args:
    chdir: /etc
- name: Start and enable mysql
  service:
   name: mysqld
   state: restarted
   enabled: yes
- name: Install mysqld python libary for Ansible
  package:
    name: MySQL-python
    state: present
- name: Grep temporary root password
  shell: grep "A temporary password" /var/log/mysqld.log | awk '{print $13}'
  register: temp_pass
- debug:
    var: temp_pass.stdout
#- name: Set mysql root password
#  mysql_user:
#    name: 'root'
#    host_all: true
#    login_user: root
#    login_password: temp_pass.stdout_lines
#    password: "{{ mysql_root_password }}"
#    update_password: always
- name: Create wordpress database
  become: false
  mysql_db:
    name: "{{ wpdb }}"
    state: present
    login_user: root
    login_password: "{{ temp_pass.stdout_lines }}"
    #login_password: "{{ mysql_root_password }}"
- name: Create wordpress user
  mysql_user:
    name: "{{ dbuser }}"
    host: "{{ dbhost }}"
    priv: 'wordpress.*:ALL'
    password: "{{ wordpress_user_password }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"


