---
- name: Download and unzip wordpress
  unarchive:
    src: http://wordpress.org/latest.tar.gz
    dest: /var/www/html
    remote_src: true
- name: Copy files to html
  copy:
    src: /var/www/html/wordpress/
    dest: /var/www/html/
    remote_src: yes
- name: Remove downloaded wordpress directory
  file:
    path: /var/www/html/wordpress
    state: absent
- name: Change file ownership of html
  file:
    path: /var/www/html/
    owner: apache
    group: apache
    recurse: yes
- name: Create wp config file
  copy:
    src: /var/www/html/wp-config-sample.php
    dest: /var/www/html/wp-config.php
    remote_src: yes
- name: Change database wordpress database name in wp-config
  shell: sed -i 's/database_name_here/{{ wpdb }}/g' wp-config.php
  args:
    chdir: /var/www/html/

- name: Change database username in wp-config
  shell: sed -i 's/username_here/{{ dbuser }}/g' wp-config.php
  args:
    chdir: /var/www/html/

- name: Change database password in wp-config
  shell: sed -i 's/password_here/{{ wordpress_user_password }}/g' wp-config.php
  args:
    chdir: /var/www/html/

- name: Change database host in wp-config
  shell: sed -i 's/localhost/{{ rdshost }}/g' wp-config.php
  args:
    chdir: /var/www/html/
  when: install_type == "server_with_rds"